name: Power Broker Node Executor
rundeckPluginVersion: 1.0
author: Alex Honor
date: 11/04/2015
version: 1.0
providers:
    - name: pbrun-exec
      service: NodeExecutor
      title: pbrun-exec
      description: Executes the command via ssh to the remote node and executs command using pbrun.
      plugin-type: script
      script-interpreter: /bin/bash
      script-file: exec.sh
      script-args: ${node.username} ${node.hostname} ${exec.command}
      config:
        - name: service_account
          title: service account
          type: String
          required: true
          description: service account to use for remote ssh connection
        - name: pbrun_cmd
          title: pbrun command
          type: String
          required: true
          description: executable to use for pbrun
